---
title: "bar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vchartr)
library(dplyr)
```


## Bar Chart

Create a bar chart :

```{r bar-chart}
electricity_mix %>% 
  filter(country == "South Korea") %>% 
  arrange(desc(generation)) %>% 
  vbar(
    aes(source, generation)
  ) %>% 
  v_colors("#5E81AC") %>% 
  v_axes(
    position = "left",
    label = list(
      formatMethod = JS("val => `${val} TWh`")
    )
  ) %>% 
  v_labs(
    title = "South Korea electricity mix"
  )
```


Colorize bars :

```{r}
electricity_mix %>% 
  filter(country == "South Korea") %>% 
  arrange(desc(generation)) %>% 
  vbar(
    aes(source, generation, fill = source)
  ) %>%
  v_specs(xField = "x") %>% # <- use only 'x' aesthetic on x-axis
  v_specs_legend(visible = FALSE) %>%
  v_specs_colors_manual(
    "oil" = "#80549f",
    "coal" = "#a68832",
    "solar" = "#d66b0d",
    "gas" = "#f20809",
    "wind" = "#72cbb7",
    "hydro" = "#2672b0",
    "nuclear" = "#e4a701"
  )
```



## Horizontal Bar Chart

Create a basic horizontal bar chart with :

```{r horizontal}
vbar(
  top_generation,
  aes(country, electricity_generation), 
  direction = "horizontal"
) %>% 
  v_specs(
    label = list(visible = TRUE)
  ) %>% 
  v_specs_colors("#8FBCBB") %>% 
  v_labs(
    title = "Top electricity-generating countries",
    subtitle = "Data for 2023, source: Our World In Data"
  )
```


Highlight a specific bar in the chart :

```{r highlight-bar}
vbar(
  top_generation,
  aes(country, electricity_generation), 
  direction = "horizontal"
) %>% 
  v_specs(
    bar = list(
      style = list(
        fill = JS("datum => datum.x == 'Japan' ? '#5E81AC' : '#88C0D0'")
      )
    )
  )
```

Or : 

```{r highlight-bars}
co2_emissions %>% 
  filter(country == "China") %>% 
  vbar(
    aes(year, co2_growth_prct)
  ) %>% 
  v_specs(
    bar = list(
      style = list(
        fill = JS("datum => datum.y <= 0 ? 'forestgreen' : 'firebrick'")
      )
    )
  ) %>% 
  v_specs_axes(
    position = "left",
    title = list(
      visible = TRUE,
      text = "Annual CO₂ emissions growth (%)",
      position = "start"
    )
  ) %>% 
  v_labs(
    title = "Annual percentage growth in total emissions of carbon dioxide (CO₂)"
  )
```




## Grouped Bar Chart

A grouped bar chart with specific colors and custom legend : 

```{r grouped}
vbar(
  subset(world_electricity, type == "total"),
  aes(year, generation, fill = source)
) %>% 
  v_specs_colors_manual("Low carbon" = "#A3BE8C", "Fossil fuels" = "#4C566A") %>% 
  v_specs_legend(
    title = list(text = "Source of electricity", visible = TRUE),
    orient = "right",
    position = "start",
    item = list(focus = TRUE)
  )
```

Stack bars :

```{r grouped-stacked}
vbar(
  subset(world_electricity, type == "total"),
  aes(year, generation, fill = source),
  stack = TRUE
) %>% 
  v_specs_colors_manual("Low carbon" = "#A3BE8C", "Fossil fuels" = "#4C566A") %>% 
  v_specs_legend(
    title = list(text = "Source of electricity", visible = TRUE),
    orient = "right",
    position = "start",
    item = list(focus = TRUE)
  )
```


```{r grouped-stacked-percentage}
vbar(
  subset(world_electricity, type == "total"),
  aes(year, generation, fill = source),
  stack = TRUE, 
  percent = TRUE
) %>% 
  v_specs_colors_manual("Low carbon" = "#A3BE8C", "Fossil fuels" = "#4C566A") %>% 
  v_specs_axes(
    position = "left",
    label = list(
      formatMethod = JS("val => `${val*100}%`")
    )
  )
```



## Bar Chart with custom labels

```{r}
electricity_mix %>% 
  filter(source == "nuclear") %>% 
  arrange(desc(generation)) %>% 
  vbar(
    aes(country, generation),
    direction = "horizontal",
    dataserie_id = "myid"
  ) %>% 
  v_specs_axes(
    position = "bottom",
    visible = FALSE
  ) %>% 
  v_specs_axes(
    position = "left",
    domainLine = list(visible = FALSE),
    tick = list(visible = FALSE)
  ) %>% 
  v_specs(
    bar = list(
      style = list(cornerRadius = c(5, 5, 5, 5), height = 10)
    ),
    barBackground = list(
      visible = TRUE,
      style = list(cornerRadius = c(5, 5, 5, 5), height = 10),
      state = list(
        hover = list(
          stroke = "#D9D9D9",
          lineWidth = 1
        )
      )
    ),
    padding = list(right = 50, left = 10),
    extensionMark = list(
      list(
        type = "text",
        dataId = "myid",
        visible = TRUE,
        style = list(
          text = JS("datum => Math.round(datum.y)"),
          fontSize = 12,
          x = JS("(datum, ctx) => { return ctx.getRegion().getLayoutRect().width + 10; }"),
          y = JS("(datum, ctx) => { return ctx.valueToY([datum.x]) + ctx.yBandwidth() / 2; }"),
          textBaseline = "middle",
          textAlign = "left",
          fill = "#595959",
          size = 20
        )
      )
    )
  ) %>% 
  v_specs_tooltip(
    mark = list(title = list(visible = FALSE)),
    dimension = list(title = list(visible = FALSE)),
    style = list(shape = list(shapeType = "circle"))
  )
```

